name: IIFAR
options:
  bundleIdPrefix: com.nakamura196
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  IIFAR:
    type: application
    platform: iOS
    sources:
      - path: IIFAR
    settings:
      base:
        INFOPLIST_FILE: IIFAR/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.nakamura196.iifar
        PRODUCT_NAME: "IIIF AR"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "2"
        DEVELOPMENT_TEAM: "Q6S8JS6GWV"
        CODE_SIGN_STYLE: "Automatic"
        TARGETED_DEVICE_FAMILY: "1,2"

  IIFARUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: IIFARUITests
    dependencies:
      - target: IIFAR
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nakamura196.iifar.uitests
        GENERATE_INFOPLIST_FILE: YES
        DEVELOPMENT_TEAM: "Q6S8JS6GWV"
        CODE_SIGN_STYLE: "Automatic"

schemes:
  IIFAR:
    build:
      targets:
        IIFAR: all
        IIFARUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: IIFAR/TipJar.storekit
    test:
      targets:
        - IIFARUITests
